### ISSUE TITLE
Error on start (backtest)

### ISSUE THREAD

**Issue by jdk-sal3** [conor19w/Binance-Futures-Trading-Bot#2]
Loading Price Data
Traceback (most recent call last):
  File "Bot.py", line 826, in <module>
    price_data = load(f"C:\\Users\\conor\\Desktop\\plots_mean\\Equity_Curves_{TIME_INTERVAL}\\price_data.joblib")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\conor\\Desktop\\plots_mean\\Equity_Curves_15\\price_data.joblib'

Please add requirements file as well

**Comment by conor19w** [comment]
Turn load_data off on line 778 in Bot.py, The script is trying to load the candlestick data from the specified path  'C:\Users\conor\Desktop\plots_mean\Equity_Curves_15\price_data.joblib' , but this path is from my device where I have the data saved. For now I have not added functionality for users to load/save data. Instead you will have to pull from the server apologies, this should fix the issue.

**Comment by jdk-sal3** [comment]
Hi, thanks for your response and update.
Now I got another error (not sure if its a code error or I just don't understand how to run the strategy)

Symbols: ['DOGEUSDT', 'SOLUSDT', 'OMGUSDT', 'ADAUSDT', 'XRPUSDT', 'ETHUSDT', 'BTCUSDT', 'MATICUSDT', 'BNBUSDT', 'BAKEUSDT'] Start Balance: 2335 fee: 0.00036
15 min OHLC Candle Sticks from a period of 3 days
Traceback (most recent call last):
  File "Bot.py", line 1215, in <module>
    CAGR = ((df['cum_return'].iloc[-1])**(1/time_CAGR)-1)*100
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by conor19w** [comment]
No problem at all its good to hear some feedback, I know the code can be difficult to decipher.
* This error is caused by not running the strategy on enough data, you have 3 days worth of 15min candles which amounts to 288 data points. __((3days x 24hours x 60mins)/15mins = 288 candles)__
* To avoid NAN (not a number) errors from using indicators such as SMA's on line 946 of Bot.py, we have  
__if len(OpenStream[0])>=299:__ this basically throws away the first 299 candles.
* So one solution would be to lower 299 to something else but then you may introduce new errors if you start getting NAN values.
* A better solution would be to increase the time_period variable on line 798 to say 7 so that you have enough candles after we throw away the first 299 of them.
* I will add a better description of the test_set, test_set_length and time_period variables to the docs.
Thank you.

**Comment by jdk-sal3** [comment]
Many thanks... backtest works now.
