### ISSUE TITLE
Trade multiple coins at same time

### ISSUE THREAD

**Issue by mujahidazamcsm** [conor19w/Binance-Futures-Trading-Bot#4]
Hi @conor19w 

Thanks for sharing the code. 

I was looking to trade multiple coins at the same time by providing a list. From the code it looks like we can trade only 1 coin at a time.

Do u think that is possible to modify the code to trade multiple coins at same time?

Also some comments on the strategies would help understand them better.

**Comment by conor19w** [comment]
Hey, yeah currently you can only trade one coin per instance of the script.
Its something I'm working on at the minute though, I think it may require multi-threaded programming.
Sure I'll add in some comments, they are just examples anyways I don't think any of them are too profitable currently but maybe with some alterations they would be.

**Comment by mujahidazamcsm** [comment]
Thanks for responding. 

Havent tried this yet but would looping thru a list of coins and calling the current methods work? Or would multi-threading be the best option?

Do u also have any backtest numbers for any of these strategies?

**Comment by conor19w** [comment]
It would require a bit of adjustment, May not need multithreading unless you are trying to scalp where order execution is crucial.
But would need to implement a more Object Orientated approach I would say. I'm looking into it now anyways so hopefully within a week or so.

Sadly not no, I think some are profitable on the 15m,30m,4hr timeframe if I recall.
Most of them need some updates to be profitable and using classes rather than functions offers more freedom.

**Comment by mujahidazamcsm** [comment]
thanks again. 

I will wait for ur updates.
