### ISSUE TITLE
No open position at all

### ISSUE THREAD

**Issue by ahmadsyramdani** [conor19w/Binance-Futures-Trading-Bot#6]
I just stack here, and no open position at all. my setting like this

2021-12-13T03:57:05.000000+00:00 app[api]: Build succeeded
2021-12-13T03:57:19.644698+00:00 app[worker.1]: Combining Historical and web socket data...
2021-12-13T03:58:06.248546+00:00 app[worker.1]: Finished.
2021-12-13T03:58:06.411248+00:00 app[worker.1]: Start Balance: 201.14444027

```
start_string = '4 hour'  
Interval = '30m'  
leverage = 15 
order_Size = .03 
```

Can you upload a video on youtube?, that your code it's proven work properly. Thank you!

**Comment by nicoaraalex90** [comment]
any update on this?

**Comment by conor19w** [comment]
Hey I didn't reply as the issue was closed.
If you read the readme file you'll see that there is no default trading strategy. One must be implemented, There are examples given in TradingStrats.py but it is up to the user to do some testing and alter the strategies to suit them.
If you join the discord server you will see some ideas too and I have an example (in the Help section) of how to convert a strategy in TradingStrats.py to a more object orientated approach that is needed in Bot.py.
